name: ThinkStats2
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.7
  - jupyter
  - numpy
  - matplotlib
  - seaborn
  - pandas
  - pytables
  - scipy
  - scikit-learn
  - plotly
  - cufflinks-py
  - pip
  - pip:
    - .



